# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MatrixRain < Formula
  desc "Authentic Matrix digital rain terminal simulator written in Go"
  homepage "https://smford.github.io/matrix-rain"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"

      def install
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"

      def install
        bin.install "matrix-rain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"

      def install
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"

      def install
        bin.install "matrix-rain"
      end
    end
  end

  test do
    system "#{bin}/matrix-rain", "-version"
  end
end
